compressionLevel: 0

defaultSemverRangePrefix: ""

enableTelemetry: false

nodeLinker: node-modules
nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/git-hooks.cjs
    spec: "git-hooks"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
