name: gh-pages

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    name: Deploy to gh-pages
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=docker depName=node versioning=node
          NODE_VERSION: "20.14.0"
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@5c6e9e9f3672ce8fd37b9856193d2a537941e66c # v4.6.1
        with:
          branch: gh-pages
          folder: public
