name: Publish

on:
  push:
    branches:
      - main

concurrency: publish

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-browser-app.yml@main

  publish:
    if: github.ref_name == github.event.repository.default_branch
    name: 🔹 Publish
    needs: qa
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Upload GitHub Pages artifact
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
