name: Publish

on:
  push:
    branches:
      - main

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-browser-app.yml@1ba99b645bcdde631e6a535a8578e82edce3c562 # main

  publish:
    if: github.ref_name == github.event.repository.default_branch
    name: 🔹 Publish
    needs: qa
    permissions:
      contents: read
      id-token: write
      packages: read
      pages: write
      pull-requests: read
    uses: oliversalzburg/workflows/.github/workflows/publish-browser-app.yml@1ba99b645bcdde631e6a535a8578e82edce3c562 # main
    with:
      wants-github-release: false
