name: QA

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-browser-app.yml@1ba99b645bcdde631e6a535a8578e82edce3c562 # main

  qa-passed:
    needs:
      - qa
    name: QA Passed
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: Success
        if: ${{ success() && !(contains(needs.*.result, 'failure')) }}
        run: exit 0
