name: QA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          submodules: true

      - name: Select NodeJS version
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: lts/*

      - name: Install and Build
        run: |
          yarn install
          yarn build
