name: QA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Select NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install and Build
        run: |
          yarn install
          yarn build
